export default function () {
  return {
    status: '',
    token: localStorage.getItem('tokendoc') || '',
    user : {unit:{}},
    pedido:[],
    boolcontrolusuarios:false,
    boolregistrocategoria:false,
    boolregistrodocumento:false,
    boolaceptarsolicitudes:false,
    boolsolicitarprestamos:false,
    boolmissolicitudes:false,
    // boolusuarios:false,
    // boolrecepcion:false,
    // boolseguimiento:false,
    // booldesignacion:false,
    // boolmisrecepciones:false,
    // inventario:false,
    // ventadetalle:false,
    // historialventadetalle:false,
    // ventalocal:false,
    // historialventalocal:false,
    // empleados:false,
    // reportes:false,
    // gastos:false,
    // historialprestamo:false,
  }
}
